# Generated by Django 6.0.3 on 2026-05-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=230)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('carga_horaria', models.IntegerField(default=120)),
                ('turno', models.CharField(default='Noturno', max_length=20)),
            ],
        ),
    ]
