# Generated by Django 6.0.3 on 2026-05-27 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('estudantes', '0002_curso_alter_alunos_curso_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='cursos.curso'),
        ),
        migrations.RemoveField(
            model_name='notas',
            name='aluno',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
    ]
