# Generated by Django 6.0.3 on 2026-05-27 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=230)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('carga_horaria', models.IntegerField(default=120)),
                ('turno', models.CharField(default='Noturno', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='alunos',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='estudantes.curso'),
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=230)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='estudantes.alunos')),
            ],
        ),
    ]
